name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install NASM
      run: sudo apt-get update && sudo apt-get install -y nasm

    - name: Install dependencies
      run: make

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: foxdos-img
        path: ./disk.img
